//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address with requested id not found.
        /// </summary>
        internal static string AddressByIdNotFound {
            get {
                return ResourceManager.GetString("AddressByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner with requested id not found.
        /// </summary>
        internal static string BannerByIdNotFound {
            get {
                return ResourceManager.GetString("BannerByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart already exists.
        /// </summary>
        internal static string CartAalreadyExists {
            get {
                return ResourceManager.GetString("CartAalreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart with requested id not found.
        /// </summary>
        internal static string CartByIdNotFound {
            get {
                return ResourceManager.GetString("CartByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart with requested user id not found.
        /// </summary>
        internal static string CartByUserIdNotFound {
            get {
                return ResourceManager.GetString("CartByUserIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart is empty.
        /// </summary>
        internal static string CartIsEmpty {
            get {
                return ResourceManager.GetString("CartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart item product not found in cart.
        /// </summary>
        internal static string CartItemNotFoundInCart {
            get {
                return ResourceManager.GetString("CartItemNotFoundInCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category with requested id not found.
        /// </summary>
        internal static string CategoryByIdNotFound {
            get {
                return ResourceManager.GetString("CategoryByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentCategoryId forms a cyclical relationship between two categoriess.
        /// </summary>
        internal static string CategoryCyclicalReference {
            get {
                return ResourceManager.GetString("CategoryCyclicalReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment with requested id not found.
        /// </summary>
        internal static string CommentByIdNotFound {
            get {
                return ResourceManager.GetString("CommentByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreditCard with requested id not found.
        /// </summary>
        internal static string CreditCardByIdNotFound {
            get {
                return ResourceManager.GetString("CreditCardByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already in use.
        /// </summary>
        internal static string EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FavoriteProduct already exist.
        /// </summary>
        internal static string FavoriteProductAlreadyExist {
            get {
                return ResourceManager.GetString("FavoriteProductAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FavoriteProduct with requested id not found.
        /// </summary>
        internal static string FavoriteProductByIdNotFound {
            get {
                return ResourceManager.GetString("FavoriteProductByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password.
        /// </summary>
        internal static string InvalidCreds {
            get {
                return ResourceManager.GetString("InvalidCreds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password confirm.
        /// </summary>
        internal static string InvalidPasswordConfirm {
            get {
                return ResourceManager.GetString("InvalidPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModeratingTable with requested id not found.
        /// </summary>
        internal static string ModeratingTableByIdNotFound {
            get {
                return ResourceManager.GetString("ModeratingTableByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModeratingTable with requested name not found.
        /// </summary>
        internal static string ModeratingTableByNameNotFound {
            get {
                return ResourceManager.GetString("ModeratingTableByNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order with requested id not found.
        /// </summary>
        internal static string OrderByIdNotFound {
            get {
                return ResourceManager.GetString("OrderByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrdersHistory with requested id not found.
        /// </summary>
        internal static string OrdersHistoryByIdNotFound {
            get {
                return ResourceManager.GetString("OrdersHistoryByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords does not match.
        /// </summary>
        internal static string PasswordsNotMatch {
            get {
                return ResourceManager.GetString("PasswordsNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission with requested id not found.
        /// </summary>
        internal static string PermissionByIdNotFound {
            get {
                return ResourceManager.GetString("PermissionByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product with requested id not found.
        /// </summary>
        internal static string ProductByIdNotFound {
            get {
                return ResourceManager.GetString("ProductByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PromoCode with requested code not found.
        /// </summary>
        internal static string PromoCodeByCodeNotFound {
            get {
                return ResourceManager.GetString("PromoCodeByCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PromoCode with requested id not found.
        /// </summary>
        internal static string PromoCodeByIdNotFound {
            get {
                return ResourceManager.GetString("PromoCodeByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role already exists.
        /// </summary>
        internal static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role with requested name not found.
        /// </summary>
        internal static string RoleByNameNotFound {
            get {
                return ResourceManager.GetString("RoleByNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcategory with requested id not found.
        /// </summary>
        internal static string SubcategoryByIdNotFound {
            get {
                return ResourceManager.GetString("SubcategoryByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has already activated a promotional code.
        /// </summary>
        internal static string UserAlreadyActivatedPromoCode {
            get {
                return ResourceManager.GetString("UserAlreadyActivatedPromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with requested id not found.
        /// </summary>
        internal static string UserByIdNotFound {
            get {
                return ResourceManager.GetString("UserByIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with requested userName not found.
        /// </summary>
        internal static string UserByUserNameNotFound {
            get {
                return ResourceManager.GetString("UserByUserNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only users with moderator role can have permissions.
        /// </summary>
        internal static string UserDoesNotHaveModeratorRole {
            get {
                return ResourceManager.GetString("UserDoesNotHaveModeratorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with the same UserName already exists.
        /// </summary>
        internal static string UserNameAlreadyExists {
            get {
                return ResourceManager.GetString("UserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cannot log in.
        /// </summary>
        internal static string UserNotLoggedIn {
            get {
                return ResourceManager.GetString("UserNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewedProduct with requested id not found.
        /// </summary>
        internal static string ViewedProductByIdNotFound {
            get {
                return ResourceManager.GetString("ViewedProductByIdNotFound", resourceCulture);
            }
        }
    }
}
